gist_id: 8a9c0d9a937cf1b60c4fabd53dbb7c83
engine: https://david-pfx.github.io/PuzzleScriptNext/src/
template: main.pss
user_extensions: [scripts/filters.py]
Build:
  name: debug
Images:
  alpha: false
  max_colors: 10
Tiled:
  generate_tileset: false
